ToDoIdentity/Models/ErrorViewModel.cs
using System;

namespace ToDoIdentity.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoIdentity/Models/IdentityInputModel.cs
using System;
namespace ToDoIdentity.Models
{
    public class IdentityInputModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

ToDoIdentity/Models/ToDoItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ToDoIdentity.Models
{
    public class ToDoItem
    {
        [Key]
        public int Id { get; set; }
        public string ToDo { get; set; }
        public string UserId { get; set; }
    }
}

ToDoIdentity/Models/ViewModel.cs
using System;
namespace ToDoIdentity.Models
{
    public class ViewModel
    {
        public string UserName { get; set; }
        public ToDoItem[] Items { get; set; }
    }
}

ToDoIdentity/Controllers/IdentityController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ToDoIdentity.Models;

namespace TicketManager.Controllers
{
    [AllowAnonymous]
    public class IdentityController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public IdentityController(UserManager<IdentityUser> _userManager,
            SignInManager<IdentityUser> _signInManager)
        {
            userManager = _userManager;
            signInManager = _signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromForm] IdentityInputModel model)
        {
            var result = await signInManager.PasswordSignInAsync(model.UserName, model.Password, true, false);
            if (result.Succeeded)
            {
                return Redirect("/");
            }
            ModelState.AddModelError(string.Empty, "ログイン失敗");
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(IdentityInputModel model)
        {
            var user = new IdentityUser() { UserName = model.UserName };

            var result = await userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                await signInManager.SignInAsync(user, true);
                return Redirect("/");
            }
            else
            {
                foreach (IdentityError e in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, e.Description);
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            return Redirect("/");
        }
    }
}

ToDoIdentity/Controllers/ToDoItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoIdentity.Data;
using ToDoIdentity.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ToDoIdentity.Controllers
{
    [Authorize]
    public class ToDoItemController : Controller
    {
        private readonly ToDoContext context;
        private readonly UserManager<IdentityUser> userManager;

        public ToDoItemController(ToDoContext _context,
            UserManager<IdentityUser> _userManger)
        {
            context = _context;
            userManager = _userManger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var toDoItems = context.ToDoItems.Where(i => i.UserId == userManager.GetUserId(User));
            var model = new ViewModel()
            {
                UserName = userManager.GetUserName(User),
                Items = toDoItems.ToArray()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create([FromForm]string toDoName)
        {
            var newItem = new ToDoItem()
            {
                UserId = userManager.GetUserId(User),
                ToDo = toDoName
            };
            context.ToDoItems.Add(newItem);
            context.SaveChanges();

            return Redirect("/ToDoItem/Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var item = context.ToDoItems.FirstOrDefault(i => i.Id == id);
            context.ToDoItems.Remove(item);
            context.SaveChanges();

            return Redirect("/ToDoItem/Index");
        }
    }
}

ToDoIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ToDoItem" asp-action="Index">ToDoIdentity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoItem" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ToDoIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoIdentity/Views/ToDoItem/Index.cshtml
@model ViewModel

@{
    ViewData["Title"] = "ToDoItems";

}

<h1>@Model.UserName さんのタスク一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                タスク
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @item.ToDo
                </td>
                <td>
                    <form asp-action="Delete" asp-route-id="@item.Id">
                        <button type="submit" class="btn btn-primary">完了</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<form asp-action="Create">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="新しいタスク" name="toDoName">
    </div>
    <button type="submit" class="btn btn-primary">作成</button>
</form>